### ISSUE TITLE
dero Bullet Proofs compatibility with Monero BP

### ISSUE THREAD

**Issue by woko556** [deroproject/derosuite#10]
I am a cryptographer and I have been analyzing Dero’s Bullet Proofs and Monero Bullet Proofs. I have seen that Dero has been done some improvements to the original BP model especially the new and faster verification algorithms. But, I stumbled with big doubts that Dero’s BP implementation is efficient or correct.

By comparing Dero’s BP with Monero BP, I have found the following incompatibilities:

1. Dero is Generating a BulletProofs for each output. If there are N outputs, there will be N bulletproofs. By contrast, Monero is generating only one Bullet Proof combing all bullet proofs into a single BP. In reality, if the transaction has multiple outputs, Dero’s BP will always be 3-4x times bigger than Monero BP. I have done tests and I always get this number. I am saying this, especially because most transactions will have at least 2 outputs namely the destination amount and the change amount.

2. Dero BP is missing a few BulletProofs parameters namely taux, mu, a, b, t and all Dero Bulletproofs have always 6 elements on L and R arrays. While, Monero is compacting the bulletproofs, Monero L and R varies based on how many outputs there are.

3. Dero is forcing to generate a new array named MixRing that in Monero is not necessary.

4. Dero MLSAG signatures are different than in Monero. Dero has II signatures while Monero has SS and CC.

Why these differences? Why so many, especially because this proposed solution by Dero is less memory efficient especially for multiple outputs taking in my account that most tx have at least 2 outputs.

How was Dero Go Lang BP even tested, while they are not fully compatible with Monero Bullet Proofs?

**The most important question, is there any option in the Dero Go Lang version to change in order to switch to fully compatible Monero Bullet Proofs?**

Thanks and keep changing the crypto space!

**Comment by CaptainDero** [comment]
Welcome woko556,

**Lets start with most important question.**
Ans:  **Any reasons why should DERO ultrafast rocket bulletproofs(which are several times faster) should be compatible with other slower implemetations.**

**Ans 1:** Factually incorrect, Pls check again. See following TX for example DERO 2/2 TX size 2.461 kB and Monero TX size is Tx size: 2.6426 kB 
TX links:
https://explorer.dero.io/tx/c82421f03e94b02e0bad55143dca64a5aece03011b00bee9cb4f847ae7981c51
https://www.xmrchain.net/tx/805e627e339f80ee8b9997db5874549ebc155e8ac03dee27a8f975f6405dfa0a
Assuming block explorers are updated and working fine. 

**Ans 2:** Again Factually incorrect, See missing parameters taux, mu, a, b, t below.
https://github.com/deroproject/derosuite/blob/a0871e64b722eea8aa100eef5787abad98d4ac1a/crypto/ringct/ringct.go#L99

**Ans 3:** Old test code. Can be cleaned in future.

**Ans 4:** Can variable name change/affect mathematical/cryptographic equations and their results.

Since you have mentioned yourself as a cryptographer and audited DERO Bulletproof's code, It's good to see that you have not found any security vulns/issues in DERO BPs.
Thanks for your time and efforts. 

Dero Team.

**Comment by woko556** [comment]
Hi @CaptainDero! Thank you so much for your answers. After reading the white paper, I understood that Dero has a different implementation called "Rocket" Bulletproofs. Don't take me wrong, I am here to understand it better for a better analyze. I really like this project and i see positive things into it.


1. There are many examples when Dero transaction size is way bigger than Monero Bullet Proofs transactions.

Here are some examples:

1) 
**1 input, 2 outputs
Monero wins**

https://explorer.dero.io/tx/d40ebcb7456aead3b69a91bdbe33d3334d8a7d370194d5ae7549985706747252
https://moneroblocks.info/tx/aa7ee57d3dd546c4e7757642e1a109e3bedc50eb515ac636e2f71b7b62455ccf

Dero: 1 ring with 10 inputs ( mixin 9), 2 outputs. ~2085 bytes
Monero: 1 ring with 11 inputs (mixin 10), 2 outputs 1888 bytes

The difference is 197 bytes, about 10%

2) 
**4 inputs, 2 outputs
DERO wins**

https://explorer.dero.io/tx/c8975e0cb9308fc02905c8b3b00539f502402e5f7a79fd3360ac803a5a561ef8
https://moneroblocks.info/tx/67683b463cd76c38111f1e336e0d7a60a6d6e73fd8714167ed6b2d281e54bd45

Dero: 4 rings - 10 inputs (mixin 9), 2 outputs: ~3423 bytes
Monero: 4 rings -  11 inputs ( mixin 10), 2 outputs: 4373 bytes

Dero is with 949 bytes shorter, so dero wins with 25% shorter tx

3) 
**1 input, 3 outputs**
Monero wins by far

https://explorer.dero.io/tx/7bf59225ca868323676b60af2a42723a628acbae10c0d8b95e7bb72b6bb9c7b2
https://xmrchain.com/tx/e6328dd4a261d0eb908f993bb042f60d7cde17d284450af87d0f2efd59f4d81e

Dero: 1 ring, 10 inputs (mixin 10), 3 outputs 2.821 kb
Monero:1 rings, 11 inputs (mixin 10), 3 outputs: 2.1191 kB

difference: 630 kb, over 22% difference.

So, definitely, DERO is more memory intensive for multiple outputs than Monero BP.  There is no transaction with multiple outputs > 3 to be more efficient in DERO than in XMR.

DERO is less memory intensive for multiple inputs than Monero BulletProofs


2) I still don't get it why MixRing is present in the transaction ring ct signature. Is it optional? Can it be removed by now, and the verify function still work?

3) MlsagSigs uses II as storing vectors. Why not SS and CC?

4) BP is generating the Mu, taux, a, b, t, but Monero BP is storing them as well and not storing the V vector. I don't see these fields stored in the DERO TX raw data. This is a JSON transaction generated by DERO Rocket Bullet Proofs and DERO is not storing in the blockchain Mu, taux, a,b,t and instead is storing the V vector.

```
{"tx":{"version":2,"unlock_time":0,"Vin":[{"Amount":0,"Key_offsets":[275229,40493,30672,39793,7848,845,78],"k_image":"b8868ce416d45559dd43089e60ae8dfde2cb09e08d6847c44a6dcd37ca2f17fc"},{"Amount":0,"Key_offsets":[123321,214009,12285,5398,39572,282,97],"k_image":"726608989857fb47e3c3d98a52266a8f76acf61edfb856b17ea7817e46dddfcd"}],"Vout":[{"Amount":0,"Target":{"Key":"585a60ecb7323673ca9309e6a6ef8252ea1a829c60d52824088b47f69c736c20"}},{"Amount":0,"Target":{"Key":"d6d9b4434eb65f92673094736e024ccadc8c3ef9c5d8e1024602b307d119efbb"}}],"Extra":"AbXzgnUtvO4WK5wQMC6urEhVnhKbjazxL1T3mUW+N617","RctSignature":{"Message":"b7588a1d92eca5750bd813c14642a1987a7e2fb967e6f06cb3099d90f358ba4e","MixRing":[[{"Destination":"2f8bf5c9e5cd25999a34589bbc59f13611e21157ac05daada73f7e0b376bc078","Mask":"146a5c81f21de421983aaf8c14e1ead7aa2c80774e2c71886b251017b1461bb4"},{"Destination":"d88caa2f329c0b6f1d67be041f510ea1f0d0b15cece4c37a6284a7ea383afeaa","Mask":"42f758b7e05844157e3b18ad3839432faf4f2339439f4852d1de0993cdf62fb9"},{"Destination":"9fa324d13b62381ddc141b5983b3dbb25b7dc0677bda80ff54e7113bff891616","Mask":"d2d16dd77140b9f643fb1acc8b8d7307e4b2159da9ff19463da18c97de70f5d7"},{"Destination":"ed87ea02ec7f40e7359c20d91f9b7029e640fa64a0645968fc299a33cd3c0d44","Mask":"8d132a45b65e7bd2c101db5d84b50d90daa1a6121c96563d35f11449e9b21e02"},{"Destination":"80b283feddfa6a23afafd595279a69c2a082737c88b268de3ade320da14e5adc","Mask":"c0cf6105e56030e241307582d3cd853bd639c09371a9cba58141082c4d855629"},{"Destination":"d29b9c90c7ecd9d324292507dc0386a217355b831906bcab64140234023c9478","Mask":"06e2cf5aa63c1a4cd2bc2cac4475550a488d6999749e604b5e3cea6663783811"},{"Destination":"3fc7f7c1305b2fda3f292698b996531a5e99564b46c7a2a9cac73538d63356dc","Mask":"2a39243bf9d4cbb682ff8abd1971e7e87e844c4ef34af6c180e723be848d0fb3"}],[{"Destination":"6318f91b61b6b24a93c2d77cfc0bc99b38118aaafcfbb85419a4597b0d55ddf7","Mask":"0f60acc9da5a3eeda600c74316be3e952db2d5d095e8099f42a56f2c563f83cd"},{"Destination":"26cec6e727f65adda84f4a5c85289865b0288b0d23e72d4a382907c6238b0013","Mask":"30eeeb19d7c65efc19937314fcd2172d01a9e66280f287df0dd2e36711047315"},{"Destination":"25d09bc73dd49c7820d07555020cda2093e0679b3f3edeef366388c9bc06da08","Mask":"bd200195ae693c10b7773f5b9a088ad0b4df209e370ca2d8a13de74c01ed14f4"},{"Destination":"7c8ea4f6b3c50df0e5bcb15fede9a80ea4a88f64b842c82b36c1f5e036b3cd63","Mask":"00133ffd1f3ff1f45165f6f83fb10e43014e5dbdb8035232b00db3c562172c33"},{"Destination":"ec6fb8246cc980d20141ff16ab8e9a63bb3a0fd015f7fb4e7dbe14887fbdc8f1","Mask":"8deb6e3b614f8fde03882cff681d6994de24d61440b45383a4be206d73988191"},{"Destination":"0cbb84cf4ea42fa631a4dd9bfa6c85aab4c123be4d6f54183648dc9b98c2467d","Mask":"d8b6c4156b4442d44db860aa76083bde08f5d70b5c5fb917f400c6a3134c564a"},{"Destination":"84ebb924918ec9233766ce8e1c7ce206f7fc0e3e9180706b888716643b370105","Mask":"c6d2a977b6503fc5e49a1a41b6bc6cc7d6405478d3933b4d89fcaf982bdbffe4"}]],"ECdhInfo":[{"Mask":"9e5e72e0cddb022998b7337225ec926f1a189c78d5bc35a7f5d1e46eff1a7c06","Amount":"53dc8cb55e78ed46d191fd74c9c353b3928c9abcb0e840e5897a3f823f227e08"},{"Mask":"461eeb933cc69490387f5874b29af3746a38536554480258dce9644c8b18c406","Amount":"02d8fdf63985ee192cb6b381b231eacfe059495cc92bca586629199a3c897205"}],"OutPk":[{"Destination":"0000000000000000000000000000000000000000000000000000000000000000","Mask":"717781fb37cfb1bcd97046fdaf821d119a0ada002b0cb6d06cc604b46a58c367"},{"Destination":"0000000000000000000000000000000000000000000000000000000000000000","Mask":"d46cfa457eb54581405c9a7246034cf28fbf798d87dba92e281c4afed089f2f1"}],"Txid":"0000000000000000000000000000000000000000000000000000000000000000","BulletSigs":[{"V":["717781fb37cfb1bcd97046fdaf821d119a0ada002b0cb6d06cc604b46a58c367"],"A":"2c2e9092ed54cacfab0378e9af3216002c230693b1d5ea1ca5436038bf5f0ea5","S":"7296a74a20fcc7502fbcc3ad84747e6d2aaf71aa7f04cc6858afb0710e9f1fb8","T1":"b077c9dae8c2292db654f797be906c0a66aa58368ffe8787d099618e91535a82","T2":"6cc877ad4f02b9501c10a2341d78320a7332e0a75563d1e919143b0913fcc5e6","L":["a4225f609f75c92d94e5e7cc687f81828ab3ec0a0fd68803d1d41c88c719ed4d","7d5eb2ee9a4f3918bfe462d6d433395c17a51b01c92d6887c532b8d16501336a","4f0a11704e8fc0eca9bc5890bd8caf98e20eb229cebc2b964734def80a095670","5d1c97f83167dfef5ad6b54b734ddf9242c19a482dc67f461fd52fae863b5b28","c3277e60c5931572f81bc10e4ec09008947da0f786635dd1ab0879715d92112e","dd1bbdaf54fe52c62f6dddb7e5e1f81cf54bc408782f0648b62304e65030d6d3"],"R":["04b4d36a81d277081b467a8c9d0c8cecd4f6edced8a6d9714b62a895c2458875","da29292e82ebe18da4dc3ca32523c9e6decb3cce9e5b711f9aa6d23a3f387713","55a2c4b76a0f16014d19f5d9993fedae6520e18d3590749706387a676d712c9b","33759a17f2afc51790246413d2d1fd2fdab1e914dae9fa0e3cb36fca70fef5b1","41a3cd3b7e6789fba8caabc078da8d1d686b46badc3abc5dd6ebeb1c0c5b4a3d","b3121ec2820d4176ba85a181fa24d8ae50d293eb518191c205897e93edf68b2f"]},{"V":["d46cfa457eb54581405c9a7246034cf28fbf798d87dba92e281c4afed089f2f1"],"A":"ad36cc6114612b978df4db45022bf26af2e75bee28fce899a1175cf9bf3d3796","S":"2f1a00929ef02043369d63e5dd7e3126201107f3c10d4db91bae3b4dd4983eec","T1":"873cd82c4f85d95b22453a150d4d061b0497e7428a510237107eb8ac2705ff92","T2":"a7b5c8341a49f4bef9a9996d74aab10d6799bd5add51c7b56ced8faabf2a1c66","L":["fe48e89424623ec335054d92109739be397516383fdee1abb11189acfb165aa0","20e7fb51d55a055ae47b43d5222d0905fce04e36506c0295cd56374974aee298","5d0babdb24f148a5d74ad5e93dee99efbfc94cac4bfe41eda83205df4b93ece1","7c7853f185d3849db9886a650cfdf639903fccfc3e75b0c08e39eebfa844ba73","0179788a6adc04fb18ee04dbf531ef404d33b6ed9b65e9c200f83c79c0030ecb","c947bad211ae7a46214c93a5cd5ea9d14a721ceb3a6620abb3f42ab69847cece"],"R":["d822e744ba3c02f1f3cf6f2a69b48bc67909404104045baae247d7f5cf0ff2dd","5edc591d79d449acf8160af9bf6a5c8676928cee0745dd349043ee19b3e64382","a0fc0e6e669fa66623bd3172be693eeea54eeaa73bbe61dfc32924ed4e0c5925","3b54c3a5f8bdcab5d883bccce57cc1ff42dce4747870dfc7b097e5028eb36d1f","e4506b12dbddbccf20ee28e398e31769134945d77f237269e2868debd406cce6","7af5e6992d9e11ad81e019a64d096c8e808ed9c01046b08ab254ecfd0ab7ca3a"]}],"MlsagSigs":[{"II":["b8868ce416d45559dd43089e60ae8dfde2cb09e08d6847c44a6dcd37ca2f17fc"]},{"II":["726608989857fb47e3c3d98a52266a8f76acf61edfb856b17ea7817e46dddfcd"]}]}}}
```

5) I had problems using the RPC node from Dero to retrieve full data from transactions. I had been trying this command, but it fails and returns me the error 502 Bad Gateway.

curl -X GET https://dero.live/gettransactions?txs_hashes[0]=8f1c7a10f21e28738a8fd51ac1e88409c89895c57ac8c02ed6c5c6ddbc6f2b44 -H 'Content-Type: application/json'

6) What data are prunable? MixRing, BulletSigs, MlsagSigs ?

**Comment by CaptainDero** [comment]
Hi @woko556, You are welcome. It's good to see someone with your talent spending precious time on Dero.

**ANS 1:** Most of the effects can be attributed to mixin and Dero bulletproofs which are basically different from Monero bulletproofs implementations. 

**ANS 2 and 3 :** These are implementation details. 

**ANS 4:** All neccessary information is present in TX. You need to dig the source for full data.

**ANS 5:** Pls use following request: curl -X POST http://127.0.0.1:20206/gettransactions -d '{"txs_hashes":["8f1c7a10f21e28738a8fd51ac1e88409c89895c57ac8c02ed6c5c6ddbc6f2b44"]}' -H 'Content-Type: application/json'

**ANS 6:** Atm pruning is not supported.

Pls feel free to close the issue.

Thanks.
DERO Team
