### ISSUE TITLE
deamon for Testnet

### ISSUE THREAD

**Issue by Tupeipei** [deroproject/derosuite#15]
Is there any node for testnet? I cant find sync the blocks for the testnet.
Or how to init a new chain by myself?

**Comment by plrspro** [comment]
https://git.dero.io/DeroProject/dvm_doc/src/master/lottery_SC_guide.md

add --testnet

**Comment by Tupeipei** [comment]
YES I KNOW. But there is no peer in testnet.So I cant sync the blocks.

**Comment by trestylez** [comment]
Are you using stargate testnet? code/binaries are found here: https://git.dero.io/DeroProject and uses different seed nodes.
