### ISSUE TITLE
Multi sig support to create a gambling website?

### ISSUE THREAD

**Issue by dutegXi** [deroproject/derosuite#16]
Really great project! I love it! I mined it, it tested transactions, very fast, really impressive work!

I started about 2 weeks ago developing in PHP on a online gambling website that will be hosted on i2p and I would like to create multisig addresses to ensure best protection for my users.

Where can I find some documentation of how to use multi signature addresses? I ask for a small snippet that creates multi signature addresses and creates transaction using multi sig. Thx

**Comment by plrspro** [comment]
there are few implementations of multisig using smartcontracts, but those are still on testnet. i guess best for you will be wait for smartcontracts to be live on mainnet, then fork one of multisig contracts and edit a bit for your needs.
you can check one of my multisig contracts meanwhile: https://github.com/plrspro/dero-sc-multisig

**Comment by dutegXi** [comment]
thanks for your answer. I don't need smart contract for this app. I only need multi sig addresses? Any way how to do it. Is there support? What is MLSAG used for then?

**Comment by plrspro** [comment]
i might be wrong but there is no native multisig support and MLSAG stands for confidential transactions
---
MLSAG is an acronym for "Multilayered Linkable Spontaneous Anonymous Group". The MLSAG signatures are the type of signatures used by Shen Noether's Ring Confidential Transactions [1], based upon Gregory Maxwell's Confidential Transactions [2] and Nicolas van Saberhagen's Ring Signatures [3].

**Comment by CaptainDero** [comment]
Not possibel atm.
