### ISSUE TITLE
CLI Wallet Synchronization Reverts to 1-2 Blocks Behind Current Block 

### ISSUE THREAD

**Issue by downystreet** [deroproject/derosuite#27]
Wallet Version: Version 2.2.1-0.Atlantis.Astrobwt+03072020
OS: Fedora 33

The CLI wallet is usually a block or two behind the current block. For example, in the wallet the synchronization will appear like this 5758225/5758226 and be orange in color. Sometimes it will sync and stay green for an entire block but most of the time it will turn green like it is synced, for example 5758226/5758226, and in a fraction of a second reverts back a block or two to this 5758225/5758226 and stays unsynced until a new block is found and it does the same thing where it syncs for a fraction of a second and then reverts to 1-2 blocks behind.

**Comment by CaptainDero** [comment]
Due to Block-DAG re-ordering of blocks.
