### ISSUE TITLE
A security vulnerability submission 

### ISSUE THREAD

**Issue by Al1ex** [deroproject/derosuite#31]
Hello, I found a vulnerability which can dos nodes. I want to know how to submit vulnerability details and vulnerability reward rules. You can contact me through TG(@RedTeamPing).

**Comment by CaptainDero** [comment]
Please drop a mail at [support @ dero.io] or contact developer at discord[ discord.gg/H95TJDp ] .
There are no as such specific rules but DERO core protocol vulns has higher bounty rewards compared to others parts like wallet etc.

**Comment by Al1ex** [comment]
> Please drop a mail at [support @ dero.io] or contact developer at discord[ discord.gg/H95TJDp ] .
> There are no as such specific rules but DERO core protocol vulns has higher bounty rewards compared to others parts like wallet etc.

OK，let's discuss via discord.

**Comment by CaptainDero** [comment]
You have been replied in mail. Thank you @Al1ex .

**Comment by CaptainDero** [comment]
Vuln acknowledged and bounty rewarded.

**Comment by Al1ex** [comment]
This security issue has been resolved
