### ISSUE TITLE
Please update documentation of `get install` installation method.

### ISSUE THREAD

**Issue by gwpl** [deroproject/derosuite#37]
In https://github.com/deroproject/derosuite#installation-from-source we have recommendation to install using `go get` while in logs we see that this method is deprecated:

```
$ go get -u github.com/deroproject/derosuite/...
(...)
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
(...)       
```

Please update documentation with new `get install` method.

**Comment by Nelbert442** [comment]
Derosuite is not currently leveraging go mod, built before. 

Win: set GO111MODULE=off

Bash: export GO111MODULE="off"
