### ISSUE TITLE
Drakogang

### ISSUE THREAD

**Issue by Drakogangcom** [deroproject/derosuite#40]
https://github.com/Drakogangcom/-1/blob/Drakogangcom-patch-1/.github/workflows/painting-pictures-ent-untagged-0834f7945f4f76469d0d (1).zip#L1-L7

**Comment by nelsonblaha** [comment]
![image](https://user-images.githubusercontent.com/1343167/150372801-3021dd24-9bae-4f1d-8812-c5774decb63c.png)
